# Generated by Django 4.2.4 on 2023-08-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
