# Generated by Django 4.2.4 on 2023-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
